#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const skillRoot = path.resolve(scriptDir, '..');

function usage(exitCode = 0) {
  const text = `Usage:
  node scripts/create-deck.mjs --name <deck-name> [options]

Options:
  --title <title>       Presentation title. Defaults to the name.
  --lang <language>     HTML language tag. Defaults to zh-CN.
  --output <directory>  Output directory. Defaults to ./<deck-name>.
  --force               Overwrite generated files in an existing directory.
  --help                 Show this help message.
`;
  (exitCode === 0 ? console.log : console.error)(text.trim());
  process.exit(exitCode);
}

function parseArgs(argv) {
  const options = { lang: 'zh-CN', force: false };
  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];
    if (arg === '--help' || arg === '-h') usage(0);
    if (arg === '--force') {
      options.force = true;
      continue;
    }
    if (!arg.startsWith('--')) {
      throw new Error(`Unexpected argument: ${arg}`);
    }
    const key = arg.slice(2);
    if (!['name', 'title', 'lang', 'output'].includes(key)) {
      throw new Error(`Unknown option: ${arg}`);
    }
    const value = argv[index + 1];
    if (!value || value.startsWith('--')) {
      throw new Error(`${arg} requires a value.`);
    }
    options[key] = value;
    index += 1;
  }
  return options;
}

function slugify(value) {
  const slug = value
    .normalize('NFKC')
    .toLowerCase()
    .replace(/[^\p{L}\p{N}]+/gu, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 80);
  return slug || 'html-ppt';
}

function escapeHtml(value) {
  return value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#39;');
}

function directoryIsEmpty(directory) {
  return !fs.existsSync(directory) || fs.readdirSync(directory).length === 0;
}

function copyRuntime(outputDirectory) {
  const sourceDirectory = path.join(skillRoot, 'assets', 'runtime');
  const targetDirectory = path.join(outputDirectory, 'runtime');
  const files = ['viewport-base.css', 'deck-runtime.js', 'deck-editor.js'];
  fs.mkdirSync(targetDirectory, { recursive: true });
  for (const file of files) {
    const source = path.join(sourceDirectory, file);
    if (!fs.existsSync(source)) throw new Error(`Missing runtime asset: ${source}`);
    fs.copyFileSync(source, path.join(targetDirectory, file));
  }
}

function buildProjectReadme({ title, deckId }) {
  return `# ${title}

HTML PPT project generated by the \`ppt\` Agent Skill.

## Files

- \`index.html\` — editable development deck
- \`runtime/\` — fixed-stage player and browser editor
- \`images/\` — local presentation assets
- \`deck.json\` — project metadata

## Open

Open \`index.html\` directly in a browser. Press \`E\` to edit text or replace marked images.

## Validate and bundle

From the installed \`ppt\` Skill directory:

\`\`\`bash
node scripts/validate-deck.mjs /absolute/path/to/${deckId}/index.html
node scripts/bundle-html.mjs /absolute/path/to/${deckId}/index.html /absolute/path/to/${deckId}.html
\`\`\`

The bundled file contains local runtime files and local images as one portable HTML document.
`;
}

let options;
try {
  options = parseArgs(process.argv.slice(2));
} catch (error) {
  console.error(error.message);
  usage(2);
}

if (!options.name) {
  console.error('--name is required.');
  usage(2);
}

const title = options.title || options.name;
const deckId = slugify(options.name);
const outputDirectory = path.resolve(options.output || path.join(process.cwd(), deckId));

if (!directoryIsEmpty(outputDirectory) && !options.force) {
  console.error(`Output directory is not empty: ${outputDirectory}`);
  console.error('Use --force to overwrite generated files while preserving unrelated files.');
  process.exit(1);
}

const templatePath = path.join(skillRoot, 'assets', 'templates', 'starter.html');
if (!fs.existsSync(templatePath)) {
  console.error(`Starter template not found: ${templatePath}`);
  process.exit(1);
}

fs.mkdirSync(outputDirectory, { recursive: true });
fs.mkdirSync(path.join(outputDirectory, 'images'), { recursive: true });
copyRuntime(outputDirectory);

let html = fs.readFileSync(templatePath, 'utf8');
html = html
  .replace('<html lang="en">', `<html lang="${escapeHtml(options.lang)}">`)
  .replace('<title>HTML PPT Starter</title>', `<title>${escapeHtml(title)}</title>`)
  .replace('data-deck-id="starter-deck"', `data-deck-id="${escapeHtml(deckId)}"`)
  .replace('>A browser-editable deck</h1>', `>${escapeHtml(title)}</h1>`)
  .replaceAll('../runtime/', 'runtime/');

const metadata = {
  id: deckId,
  title,
  language: options.lang,
  density: 'speaker-led',
  style: 'unassigned',
  createdAt: new Date().toISOString(),
  generator: 'html-ppt-agent-skill'
};

fs.writeFileSync(path.join(outputDirectory, 'index.html'), html, 'utf8');
fs.writeFileSync(path.join(outputDirectory, 'deck.json'), `${JSON.stringify(metadata, null, 2)}\n`, 'utf8');
fs.writeFileSync(path.join(outputDirectory, 'README.md'), buildProjectReadme({ title, deckId }), 'utf8');
fs.writeFileSync(path.join(outputDirectory, 'images', '.gitkeep'), '', 'utf8');

console.log(`Created HTML PPT project: ${outputDirectory}`);
console.log(`Deck ID: ${deckId}`);
console.log('Next: edit index.html, validate it, then bundle it into a single HTML file.');
